print("Michael Merriman")
cars = ['Ford','Chrysler','Dodge','Ram','Jeep','Chevy','GMC']
print(cars)
print(len(cars))
cars.append('Buick')
print(cars)
print(cars[3])
cars.insert(2,'Toyota')
print(cars)
cars.pop(4)
print(cars)
cars.sort()
print(cars)